#!/bin/bash

# Guard gegen mehrfaches Laden
if [ -n "${_RUNTIME_IDS_LOADED+x}" ]; then
    return 0
fi
_RUNTIME_IDS_LOADED=1

# Contract file next to compose: catalog/<group>/<service>/contract.env
# ID_MODE:
#   puid         – LinuxServer-style PUID/PGID in env files (honored by image)
#   compose_env  – write/export PUID/PGID for compose interpolation (${PUID})
#   volume_chown – chown data dirs to USER (or CONTRACT_OWNER if set)
#   none         – IDs not used by image; still create data dirs if listed
#   root         – container expects root; document only

ensure_user_ids() {
    if [ -z "${USER_UID:-}" ] || [ -z "${USER_GID:-}" ]; then
        get_user_info || return 1
    fi
    # For docker compose variable interpolation (never touch readonly bash UID)
    export PUID="$USER_UID"
    export PGID="$USER_GID"
    return 0
}

load_service_contract() {
    local service_dir=$1
    local contract="$service_dir/contract.env"

    # Defaults
    ID_MODE="none"
    ENV_FILES=""
    DATA_DIRS=""
    CONTRACT_OWNER=""
    CONTRACT_NOTES=""

    if [ -f "$contract" ]; then
        # shellcheck disable=SC1090
        source "$contract"
    fi
}

apply_puid_to_env_files() {
    local service_dir=$1
    local env_file key
    shift

    for env_file in "$@"; do
        [ -z "$env_file" ] && continue
        if [ ! -f "$service_dir/$env_file" ]; then
            print_status "Env file missing (skip): $service_dir/$env_file" "warn"
            continue
        fi
        # Ensure keys exist, then set
        if ! grep -q '^PUID=' "$service_dir/$env_file"; then
            echo "PUID=$USER_UID" >> "$service_dir/$env_file"
        fi
        if ! grep -q '^PGID=' "$service_dir/$env_file"; then
            echo "PGID=$USER_GID" >> "$service_dir/$env_file"
        fi
        update_env_file "$service_dir" "$env_file" \
            "PUID:$USER_UID" \
            "PGID:$USER_GID" || return 1
    done
    return 0
}

write_compose_dotenv() {
    local service_dir=$1
    cat > "$service_dir/.env" <<EOF
# Generated by runtime-ids — do not commit secrets here
PUID=${USER_UID}
PGID=${USER_GID}
UID=${USER_UID}
GID=${USER_GID}
EOF
}

prepare_data_dirs() {
    local service_dir=$1
    local owner=${2:-"${USER_UID}:${USER_GID}"}
    local dir

    for dir in $DATA_DIRS; do
        [ -z "$dir" ] && continue
        mkdir -p "$service_dir/$dir" 2>/dev/null || true
        if chown -R "$owner" "$service_dir/$dir" 2>/dev/null; then
            :
        else
            print_status "Could not chown $service_dir/$dir (may need manual fix)" "warn"
        fi
        chmod -R u+rwX "$service_dir/$dir" 2>/dev/null || true
    done
}

# Apply IDs + data dirs for one service directory
apply_runtime_ids() {
    local service_dir=$1

    if [ -z "$service_dir" ] || [ ! -d "$service_dir" ]; then
        print_status "apply_runtime_ids: invalid service dir" "error"
        return 1
    fi

    ensure_user_ids || return 1
    load_service_contract "$service_dir"

    print_status "Runtime IDs for $(basename "$service_dir"): mode=$ID_MODE uid=$USER_UID gid=$USER_GID" "info"

    case "$ID_MODE" in
        puid)
            # shellcheck disable=SC2086
            apply_puid_to_env_files "$service_dir" $ENV_FILES || return 1
            write_compose_dotenv "$service_dir"
            prepare_data_dirs "$service_dir" "${USER_UID}:${USER_GID}"
            ;;
        compose_env)
            write_compose_dotenv "$service_dir"
            # shellcheck disable=SC2086
            apply_puid_to_env_files "$service_dir" $ENV_FILES || true
            prepare_data_dirs "$service_dir" "${USER_UID}:${USER_GID}"
            ;;
        volume_chown)
            local owner="${CONTRACT_OWNER:-${USER_UID}:${USER_GID}}"
            write_compose_dotenv "$service_dir"
            prepare_data_dirs "$service_dir" "$owner"
            ;;
        root|none|"")
            write_compose_dotenv "$service_dir"
            prepare_data_dirs "$service_dir" "${USER_UID}:${USER_GID}"
            if [ -n "$CONTRACT_NOTES" ]; then
                print_status "Note: $CONTRACT_NOTES" "info"
            fi
            ;;
        *)
            print_status "Unknown ID_MODE=$ID_MODE in $service_dir/contract.env" "warn"
            write_compose_dotenv "$service_dir"
            prepare_data_dirs "$service_dir" "${USER_UID}:${USER_GID}"
            ;;
    esac

    return 0
}

apply_runtime_ids_for_container() {
    local container=$1
    local service_dir
    service_dir=$(get_docker_dir "$container") || return 1
    apply_runtime_ids "$service_dir"
}
